# This is a basic workflow that is manually triggered

name: Thanks for pull request workflow

on: pull_request

jobs:
  thank:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Thanks for the PR, It will be reviewed Shortly!'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
